language: php

php:
  - 7.3

before_install:
  - cd ${TRAVIS_BUILD_DIR}

install:
  - composer install

script:
  - vendor/bin/phpcs --standard=PSR12 --ignore='vendor/*' --exclude=Generic.Files.LineLength .
  - vendor/bin/phpunit tests
