language: php

php:
  - 5.6
  - 7.1
  - 7.2
  - 7.3

before_install:
  - cd ${TRAVIS_BUILD_DIR}

install:
  - composer install

script:
  - vendor/bin/phpcs --ignore='vendor/*' --standard=PSR12
  #  --exclude=Generic.Files.LineLength .
  - vendor/bin/phpunit tests
